wind = int(input())

if 1 <= wind <=4:
    ...
elif 5 <= wind <= 10:
    pass
elif 11 <= wind <= 19:
    ...
elif wind > 19:
    ...
else:
    ...
# TODO напишите с помощью if-elif-else условие проверки скорости ветра
